
title: My Resume
url: 'http://gnostrenoff/github.io'
baseurl: "" #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Guillaume Nostrenoff
tagline: Développeur Fullstack
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: g.nostrenoff@gmail.com
phone: + 33 6 38 75 71 99
linkedin: gnooff
github: gnostrenoff


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
